micronaut:
  application:
    name: funcionarioRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    funcionario:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 10